<?php if($pack->getFiles()->count()): ?>
	<?php foreach($pack->getFiles() as $index => $file): ?>
		<div class="row">
			<div class="col-xs-6">
				<a class="link" href="/pack/<?=$pack->getId()?>/<?=$file->getName()?>">
					<?=$file->getName()?>
				</a>
			</div>
			<?php if($permission >=2): ?>
				<div class="col-xs-5 text-right">
					<i class="fa fa-pencil-square"></i>
					<?=$file->getUpdatedAt("j M o")?>
				</div>
				<div class="col-xs-1 text-right">
					<button class="btn btn-danger btn-sm" name="delete-file" pack="<?=$pack->getId()?>" file="<?=$file->getName()?>"><i class="fa fa-trash"></i></button>
				</div>
			<?php else: ?>
				<div class="col-xs-6 text-right">
					<i class="fa fa-pencil-square"></i>
					<?=$file->getUpdatedAt("j M o")?>
				</div>
			<?php endif; ?>
		</div>
		<?php if($index != $pack->getFiles()->count() - 1): ?>
			<hr />
		<?php endif; ?>
	<?php endforeach; ?>
<?php else: ?>
	<p>There are not any files here.</p>
<?php endif; ?>
