<div  class="new-pack-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<h1>Add new pack</h1>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2>Pack information</h2>
			</div>
			<form action="/pack/create" method="POST" class="form-horizontal" id="new-pack-form">
				<div class="panel-body">	
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Pack name</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="name" validation="ajax" validation-event="keyup" validation-type="name" placeholder="Example-pack-name">
						</div>
					</div>
					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">Description</label>
						<div class="col-sm-9">
							<textarea rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about your pack"></textarea>
						</div>
					</div>
					<div class="form-group">
						<label for="private" class="col-sm-3 control-label">Private</label>
						<div class="col-sm-1">
							<label class="checkbox">
								<input type="checkbox" class="form-control" name="private" value="1">
								<i class="fa checkbox-button"></i>
							</label>
						</div>
						<p class="col-sm-8 help-block">
							Sets your pack to private.
						</p>
					</div>
				</div>
				<div class="panel-footer text-right">
					<button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Save</button>
				</div>
			</form>
		</div>
	</div>

</div>