<div  class="new-pack-wrapper">
	<div class="container">
		<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		<h1>Add new pack</h1>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<form action="/create-pack" method="POST" class="form-horizontal" id="new-pack-form">
						<div class="col-sm-6">
							<div class="form-group">
								<label for="name" class="col-sm-3 control-label">Pack name</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="name" validation="ajax" validation-event="keyup" validation-type="name" placeholder="Example-pack-name">
								</div>
							</div>
							<div class="form-group">
								<label for="description" class="col-sm-3 control-label">Description</label>
								<div class="col-sm-9">
									<textarea rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about your pack"></textarea>
								</div>
							</div>
							<div class="form-group">
								<label for="tags" class="col-sm-3 control-label">Tags</label>
								<div class="col-sm-9">
									<textarea rows="2" cols="50" class="form-control" name="tags" validation="ajax" validation-event="keyup" validation-type="tags" placeholder="Add some tags to improve searching"></textarea>
								</div>
							</div>
							<div class="form-group">
								<label for="private" class="col-sm-3 control-label">Private</label>
								<div class="col-sm-1">
									<label class="checkbox">
										<input type="checkbox" class="form-control" name="private" value="1">
										<i class="fa checkbox-button"></i>
									</label>
								</div>
								<p class="col-sm-8 help-block">
									Sets your pack to private.
								</p>
							</div>
							<div class="form-group">
								<div class="col-sm-offset-8 col-sm-4">
									<button type="submit" class="btn btn-success btn-block">Save</button>
								</div>
							</div>
						</form>
					</div>
					<div class="col-sm-6">
					</div>
				</div>
			</div>
		</div>
	</div>

</div>