
<div  class="file-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<h1 id="topheading"><a href="/pack/<?=$pack->getId()?>" class="link text-muted"><?=$pack->getName()?></a> <span class="text-muted">/</span> <?=$file->getName()?></h1>
		<div class="row">
			<div class="col-sm-5 col-md-4 col-lg-3">
				<div class="panel panel-default" id="menu">
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Pack owner</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<a href="/user/<?=$pack->getOwner()->getUsername()?>" class="link"><strong><?=$pack->getOwner()->getUsername()?></strong></a>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Created</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$file->getCreatedAt("j M o")?></strong>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Updated</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$file->getUpdatedAt("j M o")?></strong>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-7 col-md-8 col-lg-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Description</h2>
					</div>
					<div class="panel-body">
						<p id="description"><?=$file->getDescription()?></p>
						<textarea id="description-edit" rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about this file."><?=$file->getDescription()?></textarea>
					</div>
					<?php if($permission >= 2): ?>
						<div class="panel-footer text-right">
							<button class="btn btn-info" name="edit-description"><i class="fa fa-pencil-square-o"></i> Edit</button>
							<button class="btn btn-success" name="save-description" pack="<?=$pack->getId()?>" file="<?=$file->getName()?>"><i class="fa fa-save"></i> Save</button>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<?php if($permission >= 2): ?>
					<div class="row">
						<div class="col-xs-7">
							<h2><?=$file->getName()?></h2>
						</div>
						<div class="col-xs-5 text-right download-buttons">
							<a class="btn btn-success" href="/pack/<?=$pack->getId()?>/<?=$file->getName()?>/content"><i class="fa fa-download"></i><span class="hidden-xs"> Download</span></a>
							<button class="btn btn-info" name="edit-code"><i class="fa fa-pencil-square-o"></i><span class="hidden-xs"> Edit</span></button>
							<button class="btn btn-success" name="save-code" pack="<?=$pack->getId()?>" file="<?=$file->getName()?>"><i class="fa fa-save"></i><span class="hidden-xs"> Save</span></button>
						</div>
					</div>	
				<?php else: ?>
					<h2><?=$file->getName()?></h2>
				<?php endif; ?>
			</div>
			<div class="panel-body">
				<form class="code">
					<textarea id="code" name="code" lang="<?=$file->getExtension()?>"><?=$file->getContent()?></textarea>
				</form>
			</div>
		</div>
	</div>
</div>