<div class="pack-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<h1><?=$pack->getName()?></h1>
		<div class="row">
			<div class="col-sm-5 col-md-4 col-lg-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Owner</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<a href="/user/<?=$pack->getOwner()->getUsername()?>" class="link"><strong><?=$pack->getOwner()->getUsername()?></strong></a>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Created</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$pack->getCreatedAt("j M o")?></strong>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Updated</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$pack->getUpdatedAt("j M o")?></strong>
							</div>
						</div>
					</div>
					<?php if($permission == 3): ?>
						<div class="panel-footer">	
							<div class="row">
								<div class="col-xs-offset-7 col-xs-5 col-sm-offset-0 col-sm-12">
									<a class="btn btn-info btn-block" href="/pack/<?=$pack->getId()?>/settings"><i class="fa fa-cog"></i> Settings</a>
								</div>
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
			<div class="col-sm-7 col-md-8 col-lg-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Description</h2>
					</div>
					<div class="panel-body">
						<p id="description"><?=$pack->getDescription()?></p>
						<textarea id="description-edit" rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about this group."><?=$pack->getDescription()?></textarea>
					</div>
					<?php if($permission == 3): ?>
						<div class="panel-footer text-right">
							<button class="btn btn-info" name="edit-description"><i class="fa fa-pencil-square-o"></i> Edit</button>
							<button class="btn btn-success" name="save-description" pack="<?=$pack->getId()?>"><i class="fa fa-save"></i> Save</button>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-8">
						<h2>Files</h2>
					</div>
					<div class="col-xs-4 text-right">
						<?php if($permission >=2): ?>
							<button class="btn btn-info"data-toggle="collapse" data-target="#upload-files-form"><i class="fa fa-file"></i> Add</button>
						<?php endif; ?>
					</div>
				</div>
			</div>

			<?php if($permission >=2): ?>
				<form action="/pack/<?=$pack->getId()?>/add-files" method="POST" enctype="multipart/form-data" id="upload-files-form" class="collapse">
					<div class="panel-body">	
						<div class="row">
							<div class="col-sm-6">
								<div class=""><input type="file" name="files[]" required multiple></div>
							</div>
						</div>
					</div>
					<div class="panel-footer text-right">
						<button class="btn btn-success" type="submit"><i class="fa fa-upload"></i> Upload</button>
					</div>
				</form>
			<?php endif; ?>

			<div class="panel-body" id="files-list">
				<?php $this->viewFile("Views/Pack/filesList.phtml"); ?>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-8">
						<h2>Comments</h2>
					</div>
					<div class="col-xs-4 text-right">
						<?php if($loggedUser): ?>
							<button class="btn btn-info" data-toggle="collapse" data-target="#comment-form"><i class="fa fa-commenting"></i> Comment</button>
						<?php endif; ?>
					</div>
				</div>
			</div>

			<?php if($loggedUser): ?>
				<form class="collapse" id="comment-form">	
					<div class="panel-body">
						<textarea id="comment" rows="2" cols="50" class="form-control" name="comment" validation="ajax" validation-event="keyup" validation-type="comment" placeholder="Write a comment for this pack."></textarea>
					</div>
					<div class="panel-footer text-right">
						<button type="button" class="btn btn-success" name="send-comment" pack="<?=$pack->getId()?>"><i class="fa fa-send"></i> Send</button>
					</div>
				</form>
			<?php endif; ?>

			<div class="panel-body" id="comments" pack="<?=$pack->getId()?>">
				<?php $this->viewFile('Views/Pack/comments.phtml'); ?>
			</div>
		</div>

	</div>

</div>