<!DOCTYPE html>
<html lang="en">
	<head>
		<base href="../">
		<meta charset="utf-8">
		<meta keywords="<?=$keywords?>" description="<?=$description?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?=$title?></title>
		<link href="Assets/bootstrap-3.3.5-dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
		<link href="Assets/font-awesome-4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="Assets/styles/style.css" rel="stylesheet" type="text/css">
		<script src="Assets/javascript/jquery-2.1.3.js"></script>
		<script src="Assets/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
	</head>
	<body>
		<header>
			<nav class="navbar navbar-default">
				<div class="container">
					<div class="navbar-header">
						<a class="navbar-brand" href="/home">
							<img class="logo" src="Assets/images/starling_white.svg" alt="logo">
						</a>
						<ul class="nav navbar-nav visible-xs">
							<li>
								<a class="nav navbar-nav visible-xs pull-right" href="#" data-toggle="modal" data-target="#sign-in-modal">Sign in</a>
							</li>
						</ul>
					</div>
					<ul class="nav navbar-nav">
						<li>
							<form class="navbar-form" role="search" action="/search" method="get">
								<div class="form-group">
									<div class="input-group">
										<input type="text" class="form-control search-input" placeholder="Search" name="search ">
										<span class="input-group-btn">
											<button type="submit" class="btn btn-default search-button"><i class="fa fa-search"></i></button>
										</span>
									</div>
								</div>
							</form>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right hidden-xs">
						<li>
							<a href="#" data-toggle="modal" data-target="#sign-in-modal">Sign in</a>
						</li>
					</ul>
				</div>
			</nav>
		</header>

		<div class="modal fade" id="sign-in-modal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i></button>
						<h2 class="modal-title">Sign in</h2>
					</div>
					<form>
					<div class="modal-body">
							 <div class="form-group">
							 	<input type="text" class="form-control" placeholder="username" required>
							 </div>
							 <div class="form-group">
							 	<input type="password" class="form-control" placeholder="password" required>
							</div>
					</div>
					<div class="modal-footer">
						<a class="btn btn-link pull-left link" href="/forgotten-password">Forgot your password?</a>
						<button type="submit" class="btn btn-default">Sign in</button>
					</div>
					</form>
				</div>
			</div>
		</div>

		<section>
			<?php $this->viewToTemplate(); ?>
		</section>
		<footer>
		</footer>
		
		<script>
			$("h1").click(function(){
				$.ajax({
					type : "get",
					url : "/home/change-color",
					dataType : "script",
				});
			});
		</script>
	</body>
</html>