<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta keywords="<?=$keywords?>" description="<?=$description?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?=$title?></title>
		<link href="/Includes/bootstrap-3.3.5-dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
		<link href="/Includes/font-awesome-4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="/Includes/styles/style.css" rel="stylesheet" type="text/css">
		<script src="/Includes/jquery-2.1.3./jquery-2.1.3.js"></script>
		<script src="/Includes/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="/Includes/Croppie/croppie.css" />
		<script src="/Includes/Croppie/croppie.min.js"></script>
		<script src="/Includes/javascript/print_r.js"></script>
		<script src="/Includes/javascript/message.js"></script>
		<script src="/Includes/javascript/validator.js"></script>
		<script src="/Includes/javascript/ajax-communicator.js"></script>
		<script src="/Includes/javascript/avatar-n-cropper.js"></script>
		<script src="/Includes/javascript/img-group-button.js"></script>
		<script src="/Includes/javascript/file.js"></script>
		<script src="/Includes/javascript/group.js"></script>
		<script src="/Includes/javascript/pack.js"></script>
		<script src="/Includes/javascript/search.js"></script>
		<script src="/Includes/javascript/pack-settings.js"></script>
		<script src="/Includes/codemirror/lib/codemirror.js"></script>
		<link rel="stylesheet" href="/Includes/codemirror/lib/codemirror.css">
		<link rel="stylesheet" href="/Includes/codemirror/theme/elegant.css">
		<script src="/Includes/codemirror/addon/mode/loadmode.js"></script>
		<script src="/Includes/codemirror/mode/meta.js"></script>
		<script src="/Includes/javascript/codemirror.conf.js"></script>
		<script src="/Includes/javascript/application.js"></script>
	</head>
	<body>
		<header>
			<nav class="navbar navbar-default">
				<div class="container">
					<div class="navbar-header">
						<a class="navbar-brand" href="/home">
							<img class="logo" src="/Includes/images/starling_white.svg" alt="logo">
						</a>
						<ul class="nav navbar-nav visible-xs">
							<?php if($loggedUser): ?>
								<li class="dropdown pull-right">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$loggedUser->getUsername()?><img class="avatar" src="<?=$loggedUser->getAvatar40()?>" tittle="<?=$loggedUser->getUsername()?> avatar" alt="<?=$loggedUser->getUsername()?> avatar"></a>
									<ul class="dropdown-menu">
										<li><a href="/profile">Profile<i class="fa fa-user"></i></a></li>
										<li><a href="/settings">Settings<i class="fa fa-cog"></i></a></li>
										<li class="divider"></li>
										<li><a href="/sign-out">Sign out<i class="fa fa-sign-out"></i></a></li>
									</ul>
								</li>
							<?php else: ?>
								<li class="text-right">	
									<a href="#" data-toggle="modal" data-target="#sign-in-modal">Sign in</a>
								</li>
							<?php endif ?>
						</ul>
					</div>
					<ul class="nav navbar-nav">
						<li>
							<form class="navbar-form" role="search" action="/search" method="get">
								<div class="form-group">
									<div class="input-group">
										<input type="text" class="form-control search-input" placeholder="Search" name="q" <?=(isset($q) ? 'value="'.$q.'"' : null)?>>
										<?=(isset($search) ? '<input type="hidden" name="search" value="'.$search.'">' : null)?>
										<span class="input-group-btn">
											<button type="submit" class="btn btn-default search-button"><i class="fa fa-search"></i></button>
										</span>
									</div>
								</div>
							</form>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right hidden-xs">
						<?php if($loggedUser): ?>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$loggedUser->getUsername()?><img class="avatar" src="<?=$loggedUser->getAvatar40()?>" tittle="<?=$loggedUser->getUsername()?> avatar" alt="<?=$loggedUser->getUsername()?> avatar"></a>
								<ul class="dropdown-menu">
									<li><a href="/profile">Profile<i class="fa fa-user"></i></a></li>
									<li><a href="/settings">Settings<i class="fa fa-cog"></i></a></li>
									<li class="divider"></li>
									<li><a href="/sign-out">Sign out<i class="fa fa-sign-out"></i></a></li>
								</ul>
							</li>
						<?php else: ?>
							<li>	
								<a href="#" data-toggle="modal" data-target="#sign-in-modal">Sign in</a>
							</li>
						<?php endif ?>
					</ul>
				</div>
			</nav>
		</header>

		<?php $this->viewFile('Views/miscellaneous/sign_in_modal.phtml'); ?>

		<section>
			<?php $this->viewToTemplate(); ?>
		</section>
		<footer>
		</footer>
	</body>
</html>