<div class="modal fade" id="authorization-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
				<h2 class="modal-title">Authoritazion</h2>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<input type="password" class="form-control" name="password" placeholder="password" required>
					<button class="btn btn-default pull-right" type="submit">Send</button>
				</div>
			</div>
		</div>
	</div>
</div>