<?php
	$currentPageNumber = (isset($_GET["page"]) ? $_GET["page"])
	$url = str_replace('/&page=[^&]*&/', "", $_SERVER["REQUEST_URI"]);
	$url .= (strpos($url, "?") === false ? "?" : "&")."page=";
?>
<div class="text-center">
	<ul class="pagination">
		<li><a href=""><i class="fa fa-chevron-left"></i></a></li>
		<?php for($i =  as $message): ?>
		<li><a href="#">1</a></li>
		<li><a href="#">2</a></li>
		<li><a href="#">3</a></li>
		<li><a href="#">4</a></li>
		<li><a href="#">5</a></li>
		<li><a href="#">6</a></li>
		<li><a href="#">7</a></li>
		<li><a href="#">&#133;</a></li>
		<li><a href="#"><i class="fa fa-chevron-right"></i></span></a></li>
	</ul>
</div>