<div class="modal fade" id="sign-in-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i></button>
				<h2 class="modal-title">Sign in</h2>
			</div>
			<form action="/sign-in" method="POST">
				<div class="modal-body">
					 <div class="form-group">
						<input type="text" class="form-control" name="username" placeholder="username" required>
					 </div>
					 <div class="form-group">
					 	<input type="password" class="form-control" name="password" placeholder="password" required>
					</div>
					<div class="row">
						<div class="col-sm-6 checkbox">
							<label>
								<input type="checkbox" name="rememberMe" value="1">
								<i class="fa checkbox-button"></i>
								Remember me
							</label>
						</div>
						<div class="col-sm-6 text-right">
							<a class="link">Did you forget your password?</a>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<a class="btn btn-info pull-left" href="/forgotten-password">Create new acount</a>
					<button type="submit" class="btn btn-default">Sign in</button>
				</div>
			</form>
		</div>
	</div>
</div>
<?php if(isset($showSignInModal) && $showSignInModal): ?>
	<script>$('#sign-in-modal').modal('show')</script>
<?php endif ?>