<!DOCTYPE html>
<html lang="en">
	<head>
		<base href="../">
		<meta charset="utf-8">
		<meta keywords="<?=$keywords?>" description="<?=$description?>">
		<title><?=$title?></title>
		<link href="Assets/bootstrap-3.3.5-dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
		<link href="Assets/font-awesome-4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="Assets/styles/style.css" rel="stylesheet" type="text/css">
		<script src="Assets/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
		<script src="Assets/javascript/jquery-2.1.3.js"></script>
	</head>
	<body>
		<header>
			<nav>
				<img id="logo"src="Assets/images/starling.svg">
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="/sign-in">Sign in</a></li>
					<li><a href="/sign-up">Sign up</a></li>
				</ul>
				<form action="/search" method="GET">
					<input type="text">
					<button type="submit"><i class="fa fa-search"></i></button>
				</form>
			</nav>
		</header>
		<section>
			<?php $this->view('Views/flash_message.phtml'); ?>
			<?php $this->view('Views/Home/index.phtml'); ?>
		</section>
		<footer>
		</footer>
		
		<script>
			$("h1").click(function(){
				$.get("/home/change-color", "", "", "script");
			});
		</script>
	</body>
</html>
<?php