<div  class="new-group-wrapper">
	<div class="container">
		<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		<h1>Add new group</h1>
			
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2>Group information</h2>
			</div>
			<div class="panel-body">
				<form action="/group/create" method="POST" class="form-horizontal" id="new-group-form">
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Group name</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="name" validation="ajax" validation-event="keyup" validation-type="name" placeholder="Example-group-name">
						</div>
					</div>
					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">Description</label>
						<div class="col-sm-9">
							<textarea rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about this group."></textarea>
						</div>
					</div>
					<div class="form-group">
						<label for="users" class="col-sm-3 control-label">Users</label>
						<div class="col-sm-9">
							<textarea rows="2" cols="50" class="form-control" name="users" placeholder="Add users to this group."></textarea>
						</div>
					</div>
					<hr />
					<div class="col-sm-offset-8 col-sm-4">
						<button type="submit" class="btn btn-success btn-block">Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>

</div>