<div  class="new-group-wrapper">
	<div class="container">
		<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		<h1>Add new group</h1>
			
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2>Group information</h2>
			</div>
			<form action="/group/create" method="POST" class="form-horizontal" id="new-group-form">
				<div class="panel-body">
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label">Group name</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="name" validation="ajax" validation-event="keyup" validation-type="name" placeholder="Example-group-name">
						</div>
					</div>
					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">Description</label>
						<div class="col-sm-9">
							<textarea rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about this group."></textarea>
						</div>
					</div>
				</div>
				<div class="panel-footer text-right">
					<button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save</button>
				</div>
			</form>
		</div>
	</div>

</div>