<div class="group-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<h1 id="name"><?=$group->getName()?></h1>
		<input class="form-control" name="name" validation="ajax" validation-event="keyup" validation-type="name" value="<?=$group->getName()?>">
		<div class="row">
			<div class="col-sm-5 col-md-4 col-lg-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Owner</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<a href="/user/<?=$group->getOwner()->getUsername()?>" class="link"><strong><?=$group->getOwner()->getUsername()?></strong></a>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Created</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getCreatedAt("j M o")?></strong>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Updated</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getUpdatedAt("j M o")?></strong>
							</div>
						</div>
					</div>
					<?php if($permission == 2): ?>
						<div class="panel-footer">	
							<div class="row">
								<div class="col-xs-9">
									<button class="btn btn-info" name="edit-name"><i class="fa fa-pencil-square-o"></i> Change name</button>
									<button class="btn btn-success" name="save-name" group="<?=$group->getId()?>"><i class="fa fa-save"></i> Save name</button>
								</div>
								<div class="col-xs-3 text-right">
									<button class="btn btn-danger" data-toggle="modal" data-target="#delete-group-modal"><i class="fa fa-trash"></i></button>
									<div class="modal fade text-left" id="delete-group-modal">
										<div class="modal-dialog">
											<div class="modal-content">
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i></button>
													<h2 class="modal-title">Delete group</h2>
												</div>
												<div class="modal-body">
													<p>Do you realy want to delete this group?</p>
												</div>
												<div class="modal-footer">
													<form action="/group/<?=$group->getId()?>/delete" method="POST">
														<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>	
													</form>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
			<div class="col-sm-7 col-md-8 col-lg-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Description</h2>
					</div>
					<div class="panel-body">
						<p id="description"><?=$group->getDescription()?></p>
						<textarea id="description-edit" rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about this group."><?=$group->getDescription()?></textarea>
					</div>
					<?php if($permission == 2): ?>
						<div class="panel-footer text-right">
							<button class="btn btn-info" name="edit-description"><i class="fa fa-pencil-square-o"></i> Edit</button>	
							<button class="btn btn-success" name="save-description" group="<?=$group->getId()?>"><i class="fa fa-save"></i> Save</button>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h2>Users</h2>
			</div>
			<div class="panel-body" id="users-list">
				<?php $this->viewFile("Views/Group/usersList.phtml"); ?>
			</div>
			<?php if($permission == 2): ?>
				<div class="panel-footer text-right">
					<button class="btn btn-success" name="save-users" group="<?=$group->getId()?>"><i class="fa fa-save"></i> Save</a>
					<button class="btn btn-info" name="add-user"><i class="fa fa-user-plus"></i> Add</a>
				</div>
			<?php endif; ?>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h2>Permissions</h2>
			</div>
			<div class="panel-body">
				<?php if($group->getPackPermissions()->count()): ?>
					<?php foreach($group->getPackPermissions() as $index => $permission): ?>
						<div class="row">
							<div class="col-xs-5">
								<a class="link" href="/pack/<?=$permission->getPack()->getId()?>">
									<?=$permission->getPack()->getName()?>
								</a>
							</div>
							<div class="col-xs-5">
								<a class="link text-muted" href="/user/<?=$permission->getPack()->getOwner()->getUsername()?>">
									<i class="fa fa-user"></i>
									<?=$permission->getPack()->getOwner()->getUsername()?>
								</a>
							</div>
							<div class="col-xs-2 text-right">
								<?php if($permission->getValue() == 0): ?>
									<i class="fa fa-ban"></i>
								<?php elseif($permission->getValue() == 1): ?>
									<i class="fa fa-eye"></i>
								<?php elseif($permission->getValue() == 2): ?>
									<i class="fa fa-pencil-square-o"></i>
								<?php endif;?>
							</div>
						</div>
						<?php if($index != $group->getPackPermissions()->count() - 1): ?>
							<hr />
						<?php endif; ?>
					<?php endforeach; ?>
				<?php else: ?>
					<p>This group have no permissions to any packs.</p>
				<?php endif; ?>
			</div>
		</div>
	</div>

</div>