<div  class="group-wrapper">
	<div class="container">
		<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		<h1><?=$group->getName()?></h1>
		<div class="row">
			<div class="col-sm-5 col-md-4 col-lg-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Owner</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<a href="/user/<?=$group->getOwner()->getUsername()?>" class="link"><strong><?=$group->getOwner()->getUsername()?></strong></a>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Created</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getCreatedAt("j M o")?></strong>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Updated</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getUpdatedAt("j M o")?></strong>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-7 col-md-8 col-lg-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Description</h2>
					</div>
					<div class="panel-body">
						<p><?=$group->getDescription()?></p>
					</div>
					<?php if($permission == 2): ?>
						<div class="panel-footer text-right">
							<button class="btn btn-success">Edit description</button>	
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-heading">
				<h2>Users</h2>
			</div>
			<div class="panel-body" id="users-list">
				<?php $this->viewFile("Views/Group/usersList.phtml"); ?>
			</div>
			<?php if($permission == 2): ?>
				<div class="panel-footer text-right">
					<button class="btn btn-success" name="save-button" group="<?=$group->getId()?>"><i class="fa fa-save"></i> Save</a>
					<button class="btn btn-success" name="add-user"><i class="fa fa-user-plus"></i> Add</a>
				</div>
			<?php endif; ?>
		</div>
	</div>

</div>