<div  class="group-wrapper">
	<div class="container">
		<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		<h1><?=$group->getName()?></h1>
		<div class="row">
			<div class="col-sm-5 col-md-4 col-lg-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Owner</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getOwner()->getUsername()?></strong>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Created</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getCreatedAt("j M o")?></strong>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-5 col-sm-6">
								<p>Updated</p>
							</div>
							<div class="col-xs-7 col-sm-6">
								<strong><?=$group->getUpdatedAt("j M o")?></strong>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-7 col-md-8 col-lg-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Description</h2>
					</div>
					<div class="panel-body">
						<p><?=$group->getDescription()?></p>
					</div>
					<?php if($isOwner): ?>
						<div class="panel-footer text-right">
							<button class="btn btn-success">Edit description</button>	
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="panel panel-default" id="user-info">
			<div class="panel-heading">
				<h2>Users</h2>
			</div>
			<div class="panel-body">
				<?php if($group->getUsers()->count()): ?>
					<?php foreach($group->getUsers() as $index => $user): ?>
						<div class="row">
							<div class="col-xs-6">
								<a class="link" href="/user/<?=$user->getUsername()?>">
									<?=$user->getUsername()?>
								</a>
							</div>
							<div class="col-xs-6 text-right added-at-wrapper">
								<i class="fa fa-user-plus"></i>
								<?=$user->getAddedToGroup($group, "j M o")?>
							</div>
						</div>
						<?php if($index != $group->getUsers()->count() - 1): ?>
							<hr />
						<?php endif; ?>
					<?php endforeach; ?>
				<?php else: ?>
					<p>There is not any user here.</p>
				<?php endif; ?>
			</div>
			<?php if($isOwner): ?>
				<div class="panel-footer text-right">
					<button class="btn btn-success">Add user <i class="fa fa-plus"></i></a>
				</div>
			<?php endif; ?>
		</div>
	</div>

</div>