
<div  class="user-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<h1>Your profile</h1>
		<div class="row">
			<div class="col-sm-4 col-md-3">
				<div class="panel panel-default" id="user-info">
					<div class="row">
						<div class="col-xs-4 col-sm-12">
							<div id="avatar-wrapper">
								<div class="img-group">
									<img id="avatar250" src="<?=$loggedUser->getAvatar250()?>" tittle="<?=$loggedUser->getUsername()?> avatar" alt="<?=$loggedUser->getUsername()?> avatar">
									<button class="fa fa-pencil-square-o img-button" id="img-edit-button"></button>
								</div>
								<div id="croppbox"></div>
								<div id="img-form-wrapper" class="panel-body">
									<form action="/user/update-avatar" method="POST" enctype="multipart/form-data" id="upload-img-form">
										<div class="row">
											<div class="col-sm-4">
												<div class="btn btn-default btn-block btn-upload"><i class="fa fa-upload"></i><input type="file" accept="image/*" name="avatar-input" required></div>
											</div>
											<div class="col-sm-offset-2 col-sm-6">
												<button class="btn btn-default pull-right btn-block" type="submit">Save</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-xs-8 col-sm-12">
							<div class="panel-body">
								<?=($loggedUser->getName() || $loggedUser->getSurname() ? "<h3>".$loggedUser->getName().($loggedUser->getName() && $loggedUser->getSurname() ? " ": null).$loggedUser->getSurname()."</h3>": null)?>
								<h3><?=$loggedUser->getUsername()?></h3>
								<p><?=$loggedUser->getEmail()?></p>
							</div>
						</div>
					</div>
					<div class="panel-footer">
						<a href="/settings" class="btn btn-info btn-block"><i class="fa fa-cog"></i> Settings</a>
					</div>
				</div>

				<div class="hidden-xs panel panel-default">
					<div class="panel-heading">
						<h2>Permissions</h2>
					</div>
					<div class="panel-body">
						<?php if($foreignPacks->count()): ?>
							<?php foreach($foreignPacks as $index => $pack): ?>
								<div class="row">
									<div class="col-xs-10">
										<div class="row">
											<div class="col-sm-12">
												<a class="link" href="/pack/<?=$pack["pack.id"]?>">
													<?=$pack["pack.name"]?>
												</a>
											</div>
											<div class="col-sm-12">
												<a class="link text-muted" href="/user/<?=$pack["user.username"]?>">
													<i class="fa fa-user"></i>
													<?=$pack["user.username"]?>
												</a>
											</div>
										</div>
									</div>
									<div class="col-xs-2">
										<?php if($pack["pack_permission.value"] == 1): ?>
											<i class="fa fa-eye"></i>
										<?php elseif($pack["pack_permission.value"] == 2): ?>
											<i class="fa fa-pencil-square-o"></i>
										<?php endif;?>
									</div>
								</div>
								<?php if($index != $foreignPacks->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p>You do not have permissions to any packs.</p>
						<?php endif; ?>
					</div>
				</div>

				<div class="hidden-xs panel panel-default">
					<div class="panel-heading">
						<h2>Groups</h2>
					</div>
					<div class="panel-body">
						<?php if($loggedUser->getGroups()->count()): ?>
							<?php foreach($loggedUser->getGroups() as $index => $group): ?>
								<div class="row">
									<div class="col-xs-6">
										<a class="link" href="/group/<?=$group->getId()?>">
											<?=$group->getName()?>
										</a>
									</div>
									<div class="col-xs-6">
										<a class="link text-muted" href="/user/<?=$group->getOwner()->getUsername()?>">
											<i class="fa fa-user"></i>
											<?=$group->getOwner()->getUsername()?>
										</a>
									</div>
								</div>
								<?php if($index != $loggedUser->getGroups()->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p>You are not in any groups.</p>
						<?php endif; ?>
					</div>
				</div>

			</div>

			<div class="col-sm-8 col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2><i class="fa fa-archive"></i> Your packs</h2>
					</div>
					<div class="panel-body">
						<?php if($loggedUser->getPacks()->count()): ?>
							<?php foreach($loggedUser->getPacks() as $index => $pack): ?>
								<div class="row">
									<div class="col-xs-5 col-md-6">
										<a class="link" href="/pack/<?=$pack->getId()?>">
											<?=$pack->getName()?>
										</a>
									</div>
									<div class="col-xs-4 col-md-2">
										<strong>
											<?=($pack->getPrivate()?"private":"public")?>
										</strong>
									</div>
									<div class="col-xs-3 col-md-4 text-right">
										<i class="fa fa-pencil-square"></i>
										<?=$pack->getUpdatedAt("j M o")?>
									</div>
								</div>
								<?php if($index != $loggedUser->getPacks()->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p>You do not have any packs yet.</p>
						<?php endif; ?>
					</div>
					<div class="panel-footer text-right">
						<a href="/pack/new" class="btn btn-success">New <i class="fa fa-archive"></i></a>
					</div>
				</div>

				<div class="panel panel-default">
					<div class="panel-heading">
						<h2><i class="fa fa-users"></i> Your groups</h2>
					</div>
					<div class="panel-body">
						<?php if($loggedUser->getMyGroups()->count()): ?>
							<?php foreach($loggedUser->getMyGroups() as $index => $group): ?>
								<div class="row">
									<div class="col-xs-6">
										<a class="link" href="/group/<?=$group->getId()?>">
											<?=$group->getName()?>
										</a>
									</div>
									<div class="col-xs-6 text-right">
										<i class="fa fa-user"></i>
										<?=$group->getUsers()->count()?>
									</div>
								</div>
								<?php if($index != $loggedUser->getMyGroups()->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p>You do not have any groups yet.</p>
						<?php endif; ?>
					</div>
					<div class="panel-footer text-right">
						<a href="/group/new" class="btn btn-success">New <i class="fa fa-users"></i></a>
					</div>
				</div>

				<div class="visible-xs panel panel-default">
					<div class="panel-heading">
						<h2>Permissions</h2>
					</div>
					<div class="panel-body">
						<?php if($foreignPacks->count()): ?>
							<?php foreach($foreignPacks as $index => $pack): ?>
								<div class="row">
									<div class="col-xs-5">
										<a class="link" href="/pack/<?=$pack["pack.id"]?>">
											<?=$pack["pack.name"]?>
										</a>
									</div>
									<div class="col-xs-5">
										<a class="link text-muted" href="/user/<?=$pack["user.username"]?>">
											<i class="fa fa-user"></i>
											<?=$pack["user.username"]?>
										</a>
									</div>
									<div class="col-xs-2">
										<?php if($pack["pack_permission.value"] == 1): ?>
											<i class="fa fa-eye"></i>
										<?php elseif($pack["pack_permission.value"] == 2): ?>
											<i class="fa fa-pencil-square-o"></i>
										<?php endif;?>
									</div>
								</div>
								<?php if($index != $foreignPacks->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p>You do not have permissions to any packs.</p>
						<?php endif; ?>
					</div>
				</div>
				<div class="visible-xs panel panel-default">
					<div class="panel-heading">
						<h2>Groups</h2>
					</div>
					<div class="panel-body">
						<?php if($loggedUser->getGroups()->count()): ?>
							<?php foreach($loggedUser->getGroups() as $index => $group): ?>
								<div class="row">
									<div class="col-xs-6">
										<a class="link" href="/group/<?=$group->getId()?>">
											<?=$group->getName()?>
										</a>
									</div>
									<div class="col-xs-6">
										<a class="link text-muted" href="/user/<?=$group->getOwner()->getUsername()?>">
											<i class="fa fa-user"></i>
											<?=$group->getOwner()->getUsername()?>
										</a>
									</div>
								</div>
								<?php if($index != $loggedUser->getGroups()->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p>You are not in any groups.</p>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>