<div class="settings-wrapper">
	<div class="container">
		<h1>Settings</h1>
		<div class="row">
			<div class="col-sm-8">
				<div class="panel panel-default">
					<div class="panel-body form-wrapper">
						<form class="form-horizontal">
							<div class="form-group">
								<label for="newUsername" class="col-sm-3 control-label">Username</label>
								<div class="col-sm-9">
									<input type="text"  disabled="disabled" class="form-control" name="newUsername" value="<?=$user->getUsername()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newEmail" class="col-sm-3 control-label">Email</label>
								<div class="col-sm-9">
									<input type="email" class="form-control" name="newEmail" value="<?=$user->getEmail()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newName" class="col-sm-3 control-label">Name</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="newName" value="<?=$user->getName()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newSurname" class="col-sm-3 control-label">Surname</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="newSurname" value="<?=$user->getSurname()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newPassword" class="col-sm-3 control-label">New password</label>
								<div class="col-sm-9">
									<input type="password" class="form-control" name="newPassword" placeholder"password">
								</div>
							</div>
							<div class="form-group">
								<label for="passwordAgain" class="col-sm-3 control-label">Password again</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="passwordAgain" placeholder"password">
								</div>
							</div>
							<?php $this->viewFile("Views/miscellaneous/authorization-modal.phtml");?>
						</form>
						<div class="col-xs-offset-3 col-sm-7">
							<div class="alert alert-danger"></div>
						</div>
						<div class="col-xs-2">
							<button type="submit" class="btn btn-default pull-right" data-toggle="modal" data-target="#authorization-modal">Save</button>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="panel panel-default" id="avatar-settings">
					<div id="avatar-wrapper">
						<div class="img-group">
							<img id="avatar250" src="<?=$user->getAvatar250()?>" tittle="<?=$user->getUsername()?> avatar" alt="<?=$user->getUsername()?> avatar">
							<button class="fa fa-pencil-square-o img-button" id="img-edit-button"></button>
						</div>
						<div id="croppbox"></div>
					</div>
					<div id="img-form-wrapper" class="panel-body">
						<form action="/avatar-update" method="POST" enctype="multipart/form-data" id="upload-img-form">
							<div class="btn btn-default btn-upload"><i class="fa fa-upload"></i><input type="file" accept="image/*" name="avatar-input" required></div>
							<button class="btn btn-default pull-right" type="submit">Save</button>
						</form>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>