<div class="settings-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<h1>Settings</h1>
		<div class="row">
			<div class="col-sm-8">
				<div class="panel panel-default">
					<form action="/update" method="POST" class="form-horizontal" id="settings-form">
						<div class="panel-body form-wrapper">
							<div class="form-group">
								<label for="newUsername" class="col-sm-3 control-label">Username</label>
								<div class="col-sm-9">
									<p class="form-control-static"><?=$loggedUser->getUsername()?></p>
								</div>
							</div>
							<div class="form-group">
								<label for="newEmail" class="col-sm-3 control-label">Email</label>
								<div class="col-sm-9">
									<input type="email" class="form-control" name="newEmail" validation="ajax" validation-event="change" validation-type="email" value="<?=$loggedUser->getEmail()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newName" class="col-sm-3 control-label">Name</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="newName" validation="ajax" validation-event="change" validation-type="name" value="<?=$loggedUser->getName()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newSurname" class="col-sm-3 control-label">Surname</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="newSurname" validation="ajax" validation-event="change" validation-type="surname" value="<?=$loggedUser->getSurname()?>">
								</div>
							</div>
							<div class="form-group">
								<label for="newPassword" class="col-sm-3 control-label">New password</label>
								<div class="col-sm-9">
									<input type="password" class="form-control" name="newPassword" validation="ajax" validation-event="keyup" validation-type="password" validation-name="Passwords">
								</div>
							</div>
							<div class="form-group">
								<label for="passwordAgain" class="col-sm-3 control-label">Password again</label>
								<div class="col-sm-9">
									<input type="password" class="form-control" name="passwordAgain" validation="compare" validation-event="keyup" validation-name="Passwords">
								</div>
							</div>
							<div class="form-group">
								<div class="col-sm-4 col-md-5 text-center">
									<div class="alert alert-info alert-form">Please verify your identity.</div>
								</div>
								<label for="authorizationPassword" class="col-sm-3 col-md-2 control-label">Password</label>
								<div class="col-sm-5">
									<input type="password" class="form-control" name="authorizationPassword" required>
								</div>
							</div>
						</div>
						<div class="panel-footer text-right">
							<button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Save</button>
						</div>
					</form>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Delete acount</h2>
					</div>
					<div class="panel-body">
						<p>If you delete your account, you have 3 months to restore it.</p>
					</div>
					<div class="panel-footer text-right">
						<button class="btn btn-danger" data-toggle="modal" data-target="#delete-account-modal"><i class="fa fa-trash"></i> Delete account</button>
						<div class="modal fade text-left" id="delete-account-modal">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i></button>
										<h2 class="modal-title">Delete account</h2>
									</div>
									<div class="modal-body">
										<p>Do you realy want to delete your account?</p>
									</div>
									<div class="modal-footer">
										<form action="/delete" method="POST">
											<div class="col-xs-8">
												<input type="password" class="form-control" placeholder="password" name="authorizationPassword">
											</div>
											<div class="col-xs-4">
												<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
											</div>	
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="panel panel-default" id="avatar-settings">
					<div class="panel-heading">
						<h2>Avatar image</h2>
					</div>
					<div id="avatar-wrapper">
						<div class="img-group">
							<img id="avatar250" src="<?=$loggedUser->getAvatar250()?>" tittle="<?=$loggedUser->getUsername()?> avatar" alt="<?=$loggedUser->getUsername()?> avatar">
							<button class="fa fa-pencil-square-o img-button" id="img-edit-button"></button>
						</div>
						<div id="croppbox"></div>
					</div>
					<div id="img-form-wrapper" class="panel-body">
						<form action="update-avatar" method="POST" enctype="multipart/form-data" id="upload-img-form">
							<div class="btn btn-default btn-upload"><i class="fa fa-upload"></i><input type="file" accept="image/*" name="avatar-input" required></div>
							<button class="btn btn-success pull-right" type="submit"><i class="fa fa-floppy-o"></i> Save</button>
						</form>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>