<div  class="user-wrapper">
	<div class="container">
		<div id="message-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<div class="row">
			<div class="col-sm-4 col-md-3">
				<div class="panel panel-default">
					<div class="row">
						<div class="col-xs-4 col-sm-12">
							<div id="avatar-wrapper">
								<div class="img-group">
									<img id="avatar250" src="<?=$user->getAvatar250()?>" tittle="<?=$user->getUsername()?> avatar" alt="<?=$user->getUsername()?> avatar">
								</div>
							</div>
						</div>
						<div class="col-xs-8 col-sm-12">
							<div class="panel-body">
								<?=($user->getName() || $user->getSurname() ? "<h3>".$user->getName().($user->getName() && $user->getSurname() ? " ": null).$user->getSurname()."</h3>": null)?>
								<h3><?=$user->getUsername()?></h3>
								<p><?=$user->getEmail()?></p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-sm-8 col-md-9">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2><?=$user->getUsername()?>'s packs</h2>
					</div>
					<div class="panel-body">
						<?php if($user->getPacks()->count()): ?>
							<?php foreach($user->getPacks() as $index => $pack): ?>
								<div class="row">
									<div class="col-xs-9">
										<a class="link" href="/pack/<?=$pack->getId()?>">
											<?=$pack->getName()?>
										</a>
									</div>
									<div class="col-xs-3 text-right">
										<i class="fa fa-pencil-square"></i>
										<?=$pack->getUpdatedAt("j M o")?>
									</div>
								</div>
								<?php if($index != $user->getPacks()->count() - 1): ?>
									<hr />
								<?php endif; ?>
							<?php endforeach; ?>
						<?php else: ?>
							<p><?=$user->getUsername()?> has no packs.</p>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>