<div class="homepage-wrapper">
	<div class="container">
		<?php //phpinfo(); ?>
		<div id="alert-box">
			<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-sm-push-6 text-right welcome">
				<h1>Welcome</h1>
				to <img src="Includes/images/starling_text.svg">
				<h2>A place to share your code</h2>
			</div>
			<div class="col-xs-12 col-sm-6 col-sm-pull-6">
				<form class="validate" action="/sign-up" method="post" id="sign-up-form">
					<h2>Sign up</h2>
					<div class="form-group" id="email-wrapper">
						<input class="form-control" type="email" name="email" id="email-input" placeholder="email" required>
					</div>
					<div class="form-group" id="username-wrapper">
						<input class="form-control" type="text" name="username" id="username-input" placeholder="username" required>
					</div>
					<div class="form-group" id="password-wrapper">
						<input class="form-control" type="password" name="password" id="password-input" placeholder="password" required>
					</div>
					<div class="form-group" id="password-again-wrapper">
						<input class="form-control" type="password" name="password-again" id="password-again-input" placeholder="password again" required>
					</div>
					<div class="row">
						<div class="col-xs-8">
							<div class="alert alert-danger alert-box"></div>
						</div>
						<div class="col-xs-4">
							<button type="submit" class="btn btn-default pull-right">Sign up</button>		
						</div>
					</div>
				</form>
			</div>
		</div>
		<div class="col-sm-12 homepage-img-wrap">
			<img class="center-block img-responsive" src="Includes/images/starling_on_tree.svg">	
		</div>
	</div>
</div>