<div  class="new-pack-permissions-wrapper">
	<div class="container">
		<?php $this->viewFile('Views/miscellaneous/flash_message.phtml'); ?>
		<h1>Add new pack</h1>

		<form action="/create-pack" method="POST" class="form-horizontal" id="new-pack-form">
			
					<div class="panel panel-default">
						<div class="panel-heading">
							<h2>Pack information</h2>
						</div>
						<div class="panel-body">
							<div class="form-group">
								<label for="name" class="col-sm-3 control-label">Pack name</label>
								<div class="col-sm-9">
									<input type="text" class="form-control" name="name" validation="ajax" validation-event="keyup" validation-type="name" placeholder="Example-pack-name">
								</div>
							</div>
							<div class="form-group">
								<label for="description" class="col-sm-3 control-label">Description</label>
								<div class="col-sm-9">
									<textarea rows="4" cols="50" class="form-control" name="description" validation="ajax" validation-event="keyup" validation-type="description" placeholder="Write something about your pack"></textarea>
								</div>
							</div>
							<div class="form-group">
								<label for="tags" class="col-sm-3 control-label">Tags</label>
								<div class="col-sm-9">
									<textarea rows="2" cols="50" class="form-control" name="tags" validation="ajax" validation-event="keyup" validation-type="tags" placeholder="Add some tags to improve searching"></textarea>
								</div>
							</div>
							<div class="form-group">
								<label for="private" class="col-sm-3 control-label">Private</label>
								<div class="col-sm-1">
									<label class="checkbox">
										<input type="checkbox" class="form-control" name="private" value="1">
										<i class="fa checkbox-button"></i>
									</label>
								</div>
								<p class="col-sm-8 help-block">
									Sets your pack to private.
								</p>
							</div>
						</div>
					</div>
				
			<div class="row">
					
					<div class="col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h2>Add permissions to users</h2>
							</div>
							<div class="panel-body">
								<div class="form-group">
									<label class="col-xs-6 control-label text-left">Username</label>
									<label class="col-xs-2 control-label text-center">View</label>
									<label class="col-xs-2 control-label text-center">Edit</label>
									<label class="col-xs-2 control-label text-center">Remove</label>
								</div>
								<div class="form-group text-center">
									<div class="col-xs-6">
										<input type="text" class="form-control" name="user0" placeholder="username">
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="user0View" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="user0Edit" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="user0Remove" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
								</div>
								<div class="form-group text-center">
									<div class="col-xs-6">
										<input type="text" class="form-control" name="user1" placeholder="username">
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="user1View" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="user1Edit" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="user1Remove" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-offset-8 col-sm-4">
										<button class="btn btn-info btn-block">Add user</button>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h2>Add permissions to groups</h2>
							</div>
							<div class="panel-body">
								<div class="form-group">
									<label class="col-xs-6 control-label text-left">Groupname</label>
									<label class="col-xs-2 control-label text-center">View</label>
									<label class="col-xs-2 control-label text-center">Edit</label>
									<label class="col-xs-2 control-label text-center">Remove</label>
								</div>
								<div class="form-group text-center">
									<div class="col-xs-6">
										<input type="text" class="form-control" name="group0" placeholder="username">
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="group0View" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="group0Edit" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="group0Remove" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
								</div>
								<div class="form-group text-center">
									<div class="col-xs-6">
										<input type="text" class="form-control" name="group1" placeholder="username">
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="group1View" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="group1Edit" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
									<div class="col-xs-2">
										<label class="checkbox">
											<input type="checkbox" class="form-control" name="group1Remove" value="1">
											<i class="fa checkbox-button"></i>
										</label>
									</div>
								</div>
								<div class="form-group">
									<div class="col-sm-offset-8 col-sm-4">
										<button class="btn btn-info btn-block">Add group</button>
									</div>
								</div>
							</div>
						</div>
					</div>

			</div>
			<hr />
					<div class="form-group">
						<div class="col-sm-offset-8 col-sm-4">
							<button type="submit" class="btn btn-success btn-block">Save</button>
						</div>
					</div>
		</form>

	</div>

</div>